#!/bin/bash

PACKAGE="${PACKAGE} telegram-desktop "
AURPACK="${AURPACK} wps-office zoom "
FLATPAK=( )
RDAEMON="${RDAEMON}  "
GDAEMON="${GDAEMON}"


## CONFIGS
if [[ -d "$appdir/distros/config" ]]; then
    cp -fr "$appdir/distros/config/"* "$appdir/config/define/"
fi